// methods.js — generated/merged from METHOD FILE.md
// Provides a read-only METHODS mapping used by the app (METHODS[slug])
// Slugs are expected to match the dish IDs generated by the app's slug() helper.

const METHODS = {
  "cheesecake-brownies": {
    prep: "20 min",
    cook: "30-35 min",
    instructions: [
      "Preheat oven to 350°F and line an 8×8 metal pan with parchment paper. Set aside.",
      "In a medium sized bowl, prepare the flax egg by mixing together. Set aside for 10 minutes to thicken.",
      "Once the flax egg has thickened, add the almond/peanut butter, cane sugar, almond milk and vanilla extract to the bowl. Mix together until uniform, then add in the gluten free flour, cocoa powder, baking powder and salt. Mix just until uniform; do not overmix.",
      "Transfer about 1/4 of the brownie batter to a small bowl and set aside. Add the remaining brownie batter to the lined pan and spread it out evenly.",
      "Prepare the cheesecake layer: mix the cream cheese alternative and sugar until smooth, then add remaining cheesecake ingredients and mix until smooth. Pour over brownie batter and spread carefully.",
      "Drop reserved brownie batter over the cheesecake layer and swirl with a knife or toothpick. Bake 35–40 minutes or until center is set. Cool completely before cutting.",
    ],
    notes: "For clean slices, wet knife between cuts. We can make the cream cheese!",
    images: [
      "https://sweetsimplevegan.com/wp-content/uploads/2020/01/Vegan-Cheesecake-Brownies-Sweet-Simple-Vegan-2-scaled.jpg",
      "https://sweetsimplevegan.com/wp-content/uploads/2020/01/Vegan-Cheesecake-Brownies-Sweet-Simple-Vegan-12-scaled.jpg"
    ]
  },

  "bbq-black-bean-burgers-with-grilled-onions-potato-wedges": {
    prep: "20 min",
    cook: "25–30 min",
    instructions: [
      "Adjust rack to top position and preheat oven to 425°F. Wash and dry produce. Cut potatoes into 1/2-inch-thick wedges. Halve, peel, and thinly slice onion; mince a few slices until you have 2 TBSP (4 TBSP for 4 servings). Drain and rinse beans. Reserve 1/2 tsp BBQ seasoning (1 tsp for 4) in a small bowl. Halve buns.",
      "Toss potatoes on a baking sheet with a drizzle of oil, salt, and pepper. Roast on top rack until golden brown and crispy, 20–25 minutes.",
      "Place half the beans (all for 4 servings) in a large bowl. Mash with a potato masher or fork until mostly smooth. Stir in minced onion, 3/4 of the tempura batter mix (all for 4), half the pepper jack, remaining BBQ seasoning, and 3 TBSP water (4 TBSP for 4) until thoroughly combined. Season with salt (~1/4 tsp; 1/2 tsp for 4) and pepper. Divide mixture into two mounds (four for 4). Set aside.",
      "Heat a drizzle of oil in a large nonstick pan over medium-high heat. Add sliced onion and season with salt. Cook, stirring occasionally, until softened and lightly browned, 8-10 minutes. Stir in half the BBQ sauce; cook until warmed through, 2-3 minutes. Remove onion to a small bowl and wash out pan.",
      "To the bowl with reserved BBQ seasoning, stir in mayonnaise, 1 tsp pickle brine (2 tsp for 4), and 1/4 tsp sugar (1/2 tsp for 4). Season to taste.",
      "Heat a drizzle of oil in the pan over medium-high. Using a rubber spatula, add bean mixture mounds and gently press to flatten into patties. Cook until bottoms are golden and crisp, 2-4 minutes. Flip, top with remaining pepper jack, cover and cook until cheese melts and bottoms are crisp, 2-4 minutes more. Transfer to a plate.",
      "Toast buns until golden. Spread cut sides of top buns with remaining BBQ sauce and bottom buns with BBQ mayo. Assemble burgers with patties, caramelized onion, and pickles. Serve with potato wedges."
    ],
    notes: [
      "Scale quantities for 4 servings as noted in the instructions.",
      "Watch onions to avoid burning; lower heat and add a splash of water if they brown too quickly.",
      "Leftovers keep 1–2 days refrigerated."
    ],
    images: [
      "https://simple-veganista.com/wp-content/uploads/2021/06/vegan-black-bean-burger_.jpg",
      "https://simple-veganista.com/wp-content/uploads/2012/08/santa-fe-mexican-black-bean-burgers-1.jpg",
      "https://simple-veganista.com/wp-content/uploads/2012/08/sante-fe-mexican-black-bean-burgers.jpg"
    ]
  },

  "sweet-spicy-bbq-bean-burgers": {
    prep: "",
    cook: "",
    instructions: [
      "Adjust rack to top position and preheat oven to 425°F. Wash and dry produce. Cut potatoes into 1/2-inch-thick wedges. Halve, peel, and thinly slice onion; mince a few slices until you have 2 TBSP (4 TBSP for 4 servings). Drain and rinse beans. Reserve 1/2 tsp BBQ seasoning (1 tsp for 4) in a small bowl. Halve buns.",
      "Toss potatoes on a baking sheet with a drizzle of oil, salt, and pepper. Roast on top rack until golden brown and crispy, 20–25 minutes.",
      "Place half the beans (all for 4 servings) in a large bowl. Mash until mostly smooth. Stir in minced onion, 3/4 of the tempura batter mix (all for 4), half the pepper jack, remaining BBQ seasoning, and 3 TBSP water (4 TBSP for 4) until combined. Season with salt (~1/4 tsp; 1/2 tsp for 4) and pepper. Divide mixture into patties and set aside.",
      "Heat oil in a large pan; add sliced onion and cook until softened and lightly browned, 8–10 minutes. Stir in half the BBQ sauce and warm through 2–3 minutes. Remove onion and wash pan.",
      "To reserved BBQ seasoning stir in mayonnaise, 1 tsp pickle brine (2 tsp for 4) and 1/4 tsp sugar (1/2 tsp for 4). Season to taste.",
      "Cook patties in pan until bottoms are golden and crisp, 2–4 minutes, flip, top with remaining pepper jack, cover and cook until cheese melts. Transfer to a plate.",
      "Toast buns, spread top with remaining BBQ sauce and bottom with BBQ mayo. Assemble burgers with patties, onion, and pickles. Serve with potato wedges."
    ],
    notes: "Scale quantities for 4 servings as noted in the instructions. Watch onions to avoid burning.",
    images: [
      "https://simple-veganista.com/wp-content/uploads/2021/06/vegan-black-bean-burger_.jpg",
      "https://simple-veganista.com/wp-content/uploads/2012/08/santa-fe-mexican-black-bean-burgers-1.jpg",
      "https://simple-veganista.com/wp-content/uploads/2012/08/sante-fe-mexican-black-bean-burgers.jpg"
    ]
  },

  "roasted-patatas-bravas": {
    prep: "5 mins",
    cook: "60 mins",
    instructions: [
      "Preheat oven to 375°F. Toss potatoes with 3 TBSP olive oil and salt. Arrange in one layer on a rimmed baking tray and roast until browned, about 50 minutes.",
      "While potatoes roast, heat 2 TBSP olive oil in a medium pot and sauté chopped onions 4–5 minutes until beginning to brown; add garlic and sauté 2 more minutes.",
      "Add white wine and reduce by half; stir in tomato paste, crushed tomatoes, Tabasco, salt, sugar and smoked paprika. Simmer and purée if desired.",
      "When potatoes are browned toss with sauce and return to oven ~10 minutes to caramelize sauce on potatoes. Serve with remaining sauce."
    ],
    notes: "Called papas bravas or patatas bravas; adjust heat and method to taste.",
    images: [
      "https://www.simplyrecipes.com/thmb/UhaQ3N_yvsZlrj5j0KjFmzdnIXs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2011__09__spanish-roasted-potatoes-horiz-a-1800-5397c56c2b274955930af5210405d1be.jpg"
    ]
  },

  "caramelised-onion-and-mushroom-pasta": {
    prep: "6 mins",
    cook: "19 mins",
    instructions: [
      "Bring a large pot of salted water to a boil and cook pasta per package directions. Reserve 1/4 cup pasta water and drain.",
      "Heat oil in a skillet over medium. Add onion, garlic and minced mushroom stems and cook about 4 minutes until softened. Add mushroom caps, cream and season; simmer 4–5 minutes.",
      "Stir in cheese and pasta until coated; loosen with reserved pasta water if needed. Garnish with extra cheese."
    ],
    notes: "Reserve pasta water to loosen the sauce.",
    images: [
      "https://www.mushroomcouncil.com/wp-content/uploads/2017/10/P01B_Pasta-with-Creamy-Mushroom-Sauce-scaled.jpg"
    ]
  },

  "smoky-jackfruit-fajitas-with-chipotle-fresh-herbs": {
    prep: "",
    cook: "",
    instructions: [
      "Heat oil in a skillet and add onion with 1/2 tsp sea salt; cook ~10 minutes until softened.",
      "Add garlic then spices (2 tsp ground cumin, 1 tsp ground coriander, 1 tsp paprika, 1 1/2 tsp dried oregano, 1 tsp dried coriander). Cook 1–2 minutes.",
      "Add drained young jackfruit and chipotle paste; break up pieces and coat with spices.",
      "Season, add peppers, lime juice and maple syrup and cook until peppers soften. Stir in coriander and serve with tortillas."
    ],
    notes: "Use young jackfruit canned in water, adjust chipotle for heat.",
    images: [
      "https://www.thelastfoodblog.com/wp-content/uploads/2021/09/jackfruit-fajitas-1.jpg",
      "https://www.thelastfoodblog.com/wp-content/uploads/2021/09/jackfruit-fajitas-step-2.jpg",
      "https://www.thelastfoodblog.com/wp-content/uploads/2021/09/jackfruit-fajitas-step-1.jpg"
    ]
  },

  "squash-sage-risotto-cakes": {
    prep: "",
    cook: "",
    instructions: [
      "Sauté garlic and onion until translucent. Add butternut squash, season and cook until slightly tender (~5 minutes).",
      "Add Arborio rice and sage; stir and add wine, cook 1 minute. Add 2 cups broth and simmer until absorbed; add more broth 1 cup at a time until rice is cooked.",
      "Turn off heat and stir in nutritional yeast, lemon juice, lemon zest and parsley. Chill risotto until firm (preferably overnight).",
      "Form risotto cakes and air fry at 350°F ~8 minutes or bake at 350°F ~20 minutes (longer for larger cakes).",
      "Optional curry sauce: sauté ginger and shallots, add lime juice/zest, coconut milk and red chili paste and simmer to thicken."
    ],
    notes: "Use short-grain rice and chill risotto well before forming cakes.",
    images: [
      "https://www.kathysvegankitchen.com/wp-content/uploads/2022/10/roisotto-cake-recipe-leftovers.jpg"
    ]
  },

  "thai-basil-tofu-and-baby-bok-choy-saut": {
    prep: "",
    cook: "",
    instructions: [
      "Pat tofu dry, cube and toss with salt and cornstarch. Sear in sesame oil over medium-high until golden (~10–15 minutes).",
      "Whisk stir-fry sauce (soy sauce, rice vinegar, brown sugar, garlic, ginger, water, cornstarch, sesame oil).",
      "Wipe pan, add sesame oil, cook onion 2 minutes then add white parts of bok choy and cook until softened (~3–4 minutes). Add green parts and pour in sauce; cook until thickened (~2 minutes).",
      "Return tofu to pan, toss to warm through and serve with rice or noodles."
    ],
    notes: "Keep leftovers up to 3 days refrigerated. Garnish with sesame seeds and green onions.",
    images: [
      "https://plantbasedjess.com/wp-content/uploads/2022/08/IMG_3947.jpg"
    ]
  },

  "tomato-red-lentil-with-herbs-soup": {
    prep: "",
    cook: "",
    instructions: [
      "Heat 2 TBSP olive oil in a large pot over medium-high. Sauté onions until softened and starting to brown (~5 minutes).",
      "Add minced garlic (2 cloves), cumin (1 tsp) and chili powder (1/2 tsp); cook 30–60 seconds until fragrant.",
      "Add rinsed red lentils (8 oz) and coat. Pour in 6 cups broth and add diced sweet potato, diced carrots, and a 15 oz can diced tomatoes. Bring to a boil, reduce heat and simmer ~20 minutes until tender.",
      "Turn off heat and stir in ~2 TBSP lemon juice and 1/4 cup fresh chopped herbs. Serve with optional olive oil, herbs, yogurt or lemon wedges."
    ],
    notes: "Use homemade or low-sodium broth if possible. Don’t skip the lemon juice — it brightens the soup.",
    images: [
      "https://www.bowlofdelicious.com/wp-content/uploads/2023/01/Red-Lentil-Soup-Process.jpg"
    ]
  },

  "curry-cauliflower-potato-soup": {
    prep: "",
    cook: "",
    instructions: [
      "Preheat oven to 450°F. Combine coriander, cumin, cinnamon, turmeric, salt, pepper and cayenne. Toss cauliflower with 1 TBSP oil and 1 TBSP spice mixture; roast until edges brown, 15–20 minutes.",
      "Meanwhile, heat 1 TBSP oil in a large pot over medium-high. Add onion and carrot and cook until starting to brown (~3–4 minutes), then reduce heat and cook until onion soft (~3–4 more minutes). Add garlic, ginger, chile and remaining spice mixture and cook 1 minute.",
      "Stir in tomato sauce, add broth, potatoes, sweet potatoes, lime zest and juice. Cover and simmer 35–40 minutes until vegetables are tender.",
      "Stir in coconut milk and roasted cauliflower, return to simmer and serve garnished with cilantro and chiles if desired."
    ],
    images: [
      "https://www.eatingwell.com/thmb/1YZpTgbL_jSDqbmE1N0oLm1jjFk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/roasted-cauliflower-and-potato-curry-soup-ingredients-2899-256519-4000x4000-cfa2babadbfb4d038e270b7dae5b80f1.jpg",
      "https://www.eatingwell.com/thmb/D8FyncSOb5KfADRAomj9O9q4BaI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/roasted-cauliflower-and-potato-curry-soup-hero-2979-256519-4000x4000-14628d763d9c4e7492bd11f115b94bf9.jpg"
    ]
  },

  "ginger-peach-muffins-with-oat-streusel": {
    prep: "",
    cook: "",
    instructions: [
      "Preheat oven to 375°F and line a muffin tin with 8 liners.",
      "Combine flaxseed and water and set aside to thicken.",
      "In a large bowl combine flour, rolled oats and baking powder. In another bowl melt coconut oil and mix with flax mixture, maple syrup, vanilla and vegan milk.",
      "Mix wet into dry until just combined, fold in diced peaches. Divide batter among 8 tins and bake 18–20 minutes or until a toothpick comes out clean.",
      "Cool completely before storing or freezing."
    ],
    notes: "Can be made oil-free with applesauce, gluten-free with 1:1 GF flour, nut-free using nut-free milk.",
    images: [
      "https://plantbasedjess.com/wp-content/uploads/2021/08/IMG_9568.jpg",
      "https://plantbasedjess.com/wp-content/uploads/2021/08/IMG_9575.jpg"
    ]
  },

  "plum-apple-crumble-with-cinnamon-almond-crunch": {
    prep: "",
    cook: "",
    instructions: [
      "Preheat oven to 180°C (fan) / 200°C conventional.",
      "Make crumble topping: mix flour and ground almonds, rub in butter until mixture resembles breadcrumbs; stir in sugar.",
      "Prepare fruit: halve plums and cut into pieces; peel, core and quarter apples then cut each quarter into three. Mix fruit with sugar and mixed spice in a baking dish.",
      "Sprinkle topping over fruit and bake 35–40 minutes until top is golden and fruit is tender. Serve immediately."
    ],
    notes: "Use ripe plums and preferred apple variety; do not press down crumble topping or it will be dense.",
    images: [
      "https://www.mrsjoneskitchen.com/wp-content/uploads/2022/05/plum-and-apple-crumble.jpg",
      "https://www.mrsjoneskitchen.com/wp-content/uploads/2022/05/plum-and-apple-crumble-ingredients.jpg"
    ]
  }
  ,
  "mango-mint-salad": {
    prep: "",
    cook: "",
    instructions: [
      "Using a sharp knife or a special peeler, julienne mango, pepper and courgette.",
      "Tear Cos lettuce leaves roughly.",
      "Whisk all the dressing ingredients together in a small bowl and set aside for the flavours to marry.",
      "In a large mixing bowl, mix together all salad ingredients apart from nuts.",
      "Mix the dressing in, adjust seasoning.",
      "Serve sprinkled with nuts and a few leaves of mint and/or coriander."
    ],
    notes: "My mango turned out to be a bit riper (and therefore yellow) than I would have liked, but it still worked as it was still firm and not overly sweet and juicy.",
    images: []
  }
  ,
  "orange-and-basil-tofu-puffs": {
    prep: "",
    cook: "",
    instructions: [
      "Press the tofu by wrapping in paper towels (or a clean dry tea towel). Place a plate or pan on top of the wrapped tofu, and put a couple of heavy books on top of that. Let the tofu press for at least 30 minutes if possible and up to an hour.",
      "Preheat the oven to 400°F and line a large baking sheet with parchment paper or spray with oil.",
      "Slice the tofu into 1-inch cubes and add them to a large ziplock bag, along with the olive oil (or soy sauce) and cornstarch. Close the bag and shake gently to coat the tofu pieces.",
      "Arrange the tofu evenly on the prepared pan, and bake for 15 minutes. Flip and bake for 15 more minutes, until the tofu pieces are crispy and lightly golden brown. Remove from oven.",
      "In a large pan (large enough to fit the tofu and sauce), add all sauce ingredients except the cornstarch and water. Bring to a boil, and cook for a minute or two.",
      "Mix the cornstarch and water in a small bowl to combine, and then add to the pot. Stir over medium-high heat constantly for a couple of minutes, until the sauce thickens.",
      "Add the baked tofu to the pan and stir to coat the tofu in the sauce. Remove from heat.",
      "Serve over brown or white rice. Sprinkle with green onions and/or sesame seeds. Add a side of steamed broccoli or cauliflower if desired."
    ],
    notes: "Serve hot over rice; garnish with green onions or sesame seeds.",
    images: [
      "https://www.noracooks.com/wp-content/uploads/2024/09/orange-tofu-4.jpg",
      "https://www.noracooks.com/wp-content/uploads/2024/09/144A5635.jpg",
      "https://www.noracooks.com/wp-content/uploads/2024/09/orange-tofu-1.jpg",
      "https://www.noracooks.com/wp-content/uploads/2024/09/orange-tofu-2.jpg",
      "https://www.noracooks.com/wp-content/uploads/2024/09/orange-tofu-3.jpg"
    ]
  }
  ,
  "smoky-poblano-refried-beans": {
    prep: "",
    cook: "",
    instructions: [
      "In a medium-sized pot, heat the oil over medium-high heat.",
      "Add the diced onion and pepper along with the salt, and cook, stirring occasionally, until starting to soften, about five minutes.",
      "Add the garlic, tomato paste, cumin, and chili powder. Cook, stirring, for one minute.",
      "Add the beans along with the bean cooking water, broth, or water.",
      "Bring to a boil.",
      "Cover, reduce heat to medium-low, and simmer for 15 minutes.",
      "Using a potato masher, the back of a wooden spoon, or an immersion blender, mash the beans until they're as smooth as you like.",
      "Stir in lime juice."
    ],
    notes: "The 3 1/2 cups beans in this recipe come from two 15.5-ounce cans, rinsed and drained, or 1 heaping cup dried beans cooked from scratch. If you prefer, use black beans instead of pinto beans. Poblano peppers provide mild heat; substitute Anaheim, Hatch, or a green bell pepper if unavailable. Use a neutral high-smoke-point oil (safflower, canola, sunflower, peanut, or vegetable blend), or bacon fat if not vegan. Beans keep up to a week refrigerated or a year frozen.",
    images: [
      "https://umamigirl.com/wp-content/uploads/2022/06/Vegan-Refried-Beans-Umami-Girl-1200-2.jpg"
    ]
  }
  ,
  "roasted-brussels-sprouts-with-balsamic-glaze": {
    prep: "",
    cook: "",
    instructions: [
      "Preheat oven to 400°F. Line a baking sheet with parchment paper.",
      "Trim ends of Brussels sprouts and remove yellow leaves. Slice all Brussels sprouts in half.",
      "In a medium bowl, combine halved Brussels sprouts, 1 tablespoon olive oil, salt to taste, and toss to combine.",
      "Spread the Brussels sprouts on the prepared baking sheet, cut side down, in a single layer without overcrowding.",
      "Roast in the preheated oven for about 20–25 minutes. During the last 5–10 minutes, turn them over for even browning so the cut sides are nicely charred but not blackened.",
      "While sprouts roast, toast the pine nuts: preheat oven to 350°F, spread pine nuts on a parchment-lined sheet, and toast for about 5 minutes, watching closely so they don't burn.",
      "Make the balsamic glaze: combine balsamic vinegar and honey (or brown sugar) in a small pot and bring gently to a boil. Reduce heat and simmer 10–15 minutes until reduced by about half and thickened to coat the back of a spoon.",
      "To assemble, place roasted Brussels sprouts in a large serving bowl, sprinkle with toasted pine nuts, and drizzle with the balsamic glaze."
    ],
    notes: "Alternatives for the balsamic dressing: use a high-quality aged balsamic (Aceto Balsamico I.G.P. or Tradizionale) as-is without reducing, or whisk 1/4 cup balsamic vinegar with 2 TBSP olive oil until emulsified and drizzle over the sprouts.",
    images: [
      "https://juliasalbum.com/wp-content/uploads/2021/11/Brussels-Sprouts-with-Balsamic-Glaze-1.jpg",
      "https://juliasalbum.com/wp-content/uploads/2021/11/brussels-sprouts.jpg",
      "https://juliasalbum.com/wp-content/uploads/2021/11/Roasted-Brussels-Sprouts-on-a-baking-sheet.jpg"
    ]
  }
  ,
  "oven-roasted-broccoli-with-fresh-herbs": {
    prep: "",
    cook: "",
    instructions: [
      "Preheat the oven to 400°F and line a baking sheet with parchment paper.",
      "Place the broccoli florets on the baking sheet. Toss with olive oil, salt, and pepper, and spread evenly on the baking sheet.",
      "Roast 15 to 22 minutes or until browned around the edges. Sprinkle with red pepper flakes, if desired.",
      "Optional: finish with a squeeze of fresh lemon juice before serving."
    ],
    notes: "I like to serve roasted broccoli with squeezes of fresh lemon juice.",
    images: [
      "https://cdn.loveandlemons.com/wp-content/uploads/2020/01/roasted-broccoli.jpg"
    ]
  }
};

// Keep METHODS global for the existing app to consume (main.js expects a global METHODS)
if (typeof window !== 'undefined') window.METHODS = METHODS;
