// methods.js — generated/merged from METHOD FILE.md
// Provides a read-only METHODS mapping used by the app (METHODS[slug])
// Slugs are expected to match the dish IDs generated by the app's slug() helper.

export const METHODS = {
  "salted-caramel-cashew-butter-fudge": {
    "prep": "5 min",
    "cook": "0 min (freeze for 1 hour)",
    "instructions": [
      "In a food processor, blend cashew butter, maple syrup, and coconut oil until completely smooth.",
      "Line a 4\" by 4\" square cake pan with parchment paper. Pour the mixture into the pan and freeze for 1 hour or until solid.",
      "Sprinkle with sea salt flakes, cut into 10 pieces, and serve or store in the freezer."
    ],
    "notes": "Creamy 3-ingredient paleo salted caramel cashew butter fudge. Healthy, easy, vegan, and has a great 'pull apart' texture. Store in the freezer for best results.",
    "images": [
      "https://paleoglutenfree.com/wp-content/uploads/2017/07/cashew-butter-fudge-1-of-19-683x1024.jpg",
      "https://paleoglutenfree.com/wp-content/uploads/2017/07/cashew-butter-fudge-9-of-19-683x1024.jpg",
    ]
  },
  "cherry-crumble": {
    "prep": "5 min",
    "cook": "15 min",
    "instructions": [
      "Preheat oven to 400°F.",
      "In a small bowl, combine oats, slivered almonds, cinnamon, and salt. Add butter and avocado oil; use a fork to mash butter and stir to combine.",
      "In another bowl, stir together cherries, vanilla extract, and cornstarch.",
      "Divide cherry mixture among 4 (8-ounce) ovenproof ramekins.",
      "Sprinkle oat mixture over the cherries.",
      "Bake for about 15 minutes, until cherries are bubbly and oats are golden brown.",
      "Let cool for 10 minutes before serving."
    ],
    "notes": "This dessert highlights the natural sweetness of cherries without added sugar. The crumble topping provides fiber and a satisfying crunch. Baking in ramekins makes individual portions easy to serve.",
    "images": [
      "https://www.eatingwell.com/thmb/ex5UTaAcKw8UW6wSumInRshPxyE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/EW-Cherry-Crumble-step-01-2172_preview_maxWidth_4000_maxHeight_4000_ppi_300_quality_100-e5a21635f2ff44bda78d5592a4e0af25.jpg",
      "https://www.eatingwell.com/thmb/3LYlmI7LD35cm8Rp8wcZzrkTVt4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/EW-Cherry-Crumble-step-02-2173_preview_maxWidth_4000_maxHeight_4000_ppi_300_quality_100-0f45107a933042cd800e3d706a59ed3b.jpg",
      "https://www.eatingwell.com/thmb/3bCwZGzyT6FnPymxfYPJobjWNXI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/EW-Cherry-Crumble-step-04-2179_preview_maxWidth_4000_maxHeight_4000_ppi_300_quality_100-e071ff166fbf4263a699051228ac531e.jpg",
    ]
  },
  "cranberry-orange-muffins": {
    "prep": "10 min",
    "cook": "20 min",
    "instructions": [
      "Preheat oven to 400°F. Grease muffin cups or line with muffin liners.",
      "In a bowl, combine flours, sugars, salt, baking powder, cinnamon, and nutmeg.",
      "Add almondmilk, melted coconut oil, mashed banana, and orange zest. Stir until just moistened.",
      "Fold in fresh cranberries. Fill muffin cups ¾ full.",
      "Prepare streusel topping by combining flour, light brown sugar, cinnamon, salt, and melted coconut oil. Use fingers to combine into coarse crumbles.",
      "Divide streusel evenly over muffin cups.",
      "Bake for 18–22 minutes, or until a toothpick inserted comes out clean."
    ],
    "notes": "These muffins are soft, fluffy, and packed with orange and cranberry flavor. The almond crumble topping adds a crunchy texture. Makes 11 muffins.",
    "images": [
      "https://www.bakerita.com/wp-content/uploads/2015/12/Cranberry-Orange-Muffins-Vegan.jpg",
      "https://www.bakerita.com/wp-content/uploads/2015/12/Cranberry-Orange-Muffins-Vegan-9.jpg",
    ]
  },
  "pesto-gnocchi": {
    "prep": "5 min",
    "cook": "10 min",
    "instructions": [
      "Heat some olive oil in a large pan over medium heat. Add the gnocchi and cook for 10 minutes, stirring every few minutes.",
      "Roughly chop the artichoke hearts and the sun-dried tomatoes. Cut the cherry tomatoes into halves.",
      "Place everything in a large bowl and stir carefully.",
      "For the vegan pesto rosso sauce: add the sun-dried tomatoes, basil, garlic, pine nuts, and Parmesan (optional) to a food processor or blender. Pulse until a thick, coarse paste forms. Slowly drizzle in olive oil while the machine is running until you reach the desired consistency. Season with salt and pepper to taste.",
      "Combine the cooked gnocchi with the prepared pesto rosso sauce and mix gently to coat everything evenly."
    ],
    "notes": "Make sure to use a large pan, so you can spread out the gnocchi in a single layer. You don't want the pan to be overcrowded. Otherwise the gnocchi will take much longer and won't become as crispy. I don't recommend boiling the gnocchi for this recipe. If you're not a fan of arugula, you could use baby spinach instead.",
    "images": [
      "https://veganheaven.org/wp-content/uploads/2021/07/Pesto-Gnocchi-8.jpg",
      "https://veganheaven.org/wp-content/uploads/2021/07/Pesto-Gnocchi-4.jpg",
      "https://veganheaven.org/wp-content/uploads/2021/07/Pesto-Gnocchi-3.jpg",
      "https://veganheaven.org/wp-content/uploads/2021/07/Pesto-Gnocchi-30.jpg",
      "https://veganheaven.org/wp-content/uploads/2021/07/Pesto-Gnocchi-6.jpg",
    ]
  },
  "sweet-chili-pad-thai": {
    "prep": "10 min",
    "cook": "10-15 min",
    "instructions": [
      "Pad Thai Sauce: Add the sugar to a light-colored saucepan or skillet. Heat over medium heat for 2-3 minutes or until sugar has melted. Do not stir. Keep heating until the sugar gets a golden brown color and turns into caramel.",
      "As soon as the sugar has caramelized, deglaze with the 2 tablespoons of water. Be careful, as it will spit. Add vegan fish sauce, sweet chili sauce, soy sauce, tamarind juice, and toasted rice powder if using. Let simmer for 1 minute or until caramel has melted. Transfer the sauce to a small bowl and set aside.",
      "Pad Thai: Bring a large pot of water to a boil and cook the rice noodles according to package instructions.",
      "In the meantime, heat oil in a skillet or wok over medium heat. Add minced garlic and shallot, and cook for 2-3 minutes until fragrant.",
      "Add scrambled tofu and cook for another minute. Optionally, add a pinch of turmeric for color and kala namak for an eggy taste.",
      "Add drained noodles, bean sprouts, Chinese chives, and the sauce. Cook 2-3 minutes, stirring to coat the noodles.",
      "Remove from heat, top with crushed peanuts, a squeeze of lime, and serve immediately."
    ],
    "notes": "To make tamarind juice: Add 3 tablespoons of tamarind pulp to a bowl. Cover with 1/3 cup boiling water and let rest for 10-15 minutes. Strain through a fine sieve and discard the pulp. This Pad Thai keeps for up to 3 days in the refrigerator.",
    "images": [
      "https://fullofplants.com/wp-content/uploads/2022/02/easy-vegan-pad-thai-noodle-dish-with-bean-sprouts-7-1400x2100.jpg",
    ]
  },
  "sweet-potato-enchiladas": {
    "prep": "15 min",
    "cook": "20-25 min",
    "instructions": [
      "Preheat oven to 375°F.",
      "In a large saucepan, place a steamer basket over 1 inch of water. Place sweet potato, onion, and red pepper in basket. Bring water to a boil, then reduce heat to maintain a simmer. Steam, covered, until tender, 15-20 minutes.",
      "Transfer vegetables to a large bowl. Mash vegetables, gradually adding cilantro, spices, and pepper to reach desired consistency. Stir in black beans.",
      "Spread 1/3 cup enchilada sauce into a greased 13x9-inch baking dish. Place 1/3 cup vegetable mixture in center of each tortilla; sprinkle with 4 teaspoons cheese. Roll up and place in prepared dish, seam side down.",
      "Top with remaining enchilada sauce; sprinkle with remaining cheese.",
      "Bake, uncovered, until casserole is heated through and cheese is melted, 20-25 minutes. Serve with optional toppings as desired."
    ],
    "notes": "",
    "images": [
      "https://www.tasteofhome.com/wp-content/uploads/2024/08/Smoky-Sweet-Potato-and-Black-Bean-Enchiladas_TOHD24_189973_MollyBolton_-4.jpg?fit=700%2C1024",
      "https://www.tasteofhome.com/wp-content/uploads/2024/08/Smoky-Sweet-Potato-and-Black-Bean-Enchiladas_TOHD24_189973_MollyBolton_-3.jpg?fit=700%2C1024",
      "https://www.tasteofhome.com/wp-content/uploads/2024/08/Smoky-Sweet-Potato-and-Black-Bean-Enchiladas_TOHD24_189973_MollyBolton_-2.jpg?fit=700%2C1024",
      "https://www.tasteofhome.com/wp-content/uploads/2024/08/Smoky-Sweet-Potato-and-Black-Bean-Enchiladas_TOHD24_189973_MollyBolton_-1.jpg?fit=700%2C1024",
      "https://www.tasteofhome.com/wp-content/uploads/2024/08/Smoky-Sweet-Potato-and-Black-Bean-Enchiladas_TOHD24_189973_MollyBolton_.jpg?fit=700%2C1024",
    ]
  },
  "creamy-green-bean-mushroom-casserole": {
    "prep": "25 min",
    "cook": "25 min",
    "instructions": [
      "Place the sauce ingredients (water or broth, cashews, and flour) into a blender, and blend for 10 seconds. Set aside.",
      "Bring 6 cups of water to a boil in a soup pot. Add the beans and boil on high for 5 to 6 minutes. Drain and transfer to a bowl of ice water for 5 minutes. Drain again and set aside.",
      "Preheat oven to 350°F. Heat 1 tablespoon of water in the same soup pot over medium-high heat. When water sputters, add the onion and mushrooms and cook 3-4 minutes, adding water as needed. Add garlic and rosemary and stir for 1 more minute. Remove from heat.",
      "Blend the sauce again until smooth. Stir the sauce into the pot with onions and mushrooms, then add green beans. Transfer to a baking dish and bake uncovered for 20 minutes.",
      "Serve immediately as is or topped with ground black pepper and/or dried onions."
    ],
    "notes": "Dried onions: Used dried minced onion and dried shallots from the spice store as a garnish instead of French’s French-Fried Onions. Mushrooms: Can substitute with cauliflower, broccoli, peppers, or cubed winter squash. Baking dish: 8x8-inch or similar works. Flour: Millet flour used here, but oat or rice flour works too.",
    "images": [
      "https://www.straightupfood.com/blog/wp-content/uploads/2021/11/Green-Bean-Casserole_TI-720x900.jpg",
      "https://www.straightupfood.com/blog/wp-content/uploads/2021/11/Green-Bean-Casserole_beans-768x768.jpg",
      "https://www.straightupfood.com/blog/wp-content/uploads/2021/11/Green-Bean-Casserole_ice-water-768x768.jpg",
      "https://www.straightupfood.com/blog/wp-content/uploads/2021/11/Green-Bean-Casserole_mushrooms-onion-garlic-rosemary-768x768.jpg",
      "https://www.straightupfood.com/blog/wp-content/uploads/2021/11/Green-Bean-Casserole_saute-768x768.jpg",
      "https://www.straightupfood.com/blog/wp-content/uploads/2021/11/Green-Bean-Casserole_adding-sauce-768x768.jpg",
      "https://www.straightupfood.com/blog/wp-content/uploads/2021/11/Green-Bean-Casserole_dried-onions-768x768.jpg",
    ]
  },

  "creamy-mushroom-thyme-soup": {
    "prep": "10 min",
    "cook": "20-25 min",
    "instructions": [
      "Place a dry pot over medium heat. Melt butter and pour in olive oil. Add chopped onion and minced garlic, sauté until translucent.",
      "Add sliced mushrooms and stir, allowing them to release moisture and become golden brown.",
      "Sprinkle in crushed thyme leaves and season with salt and pepper.",
      "Add vegetable broth (or chicken broth if preferred). Bring to a boil, then reduce heat and simmer for 15-20 minutes.",
      "Blend in cream in small batches until fully integrated, then simmer for an additional 5 minutes.",
      "Garnish with freshly chopped parsley and serve with a slice of crusty bread."
    ],
    "notes": "This hearty soup combines the earthy flavor of mushrooms with aromatic thyme, perfect for autumn comfort.",
    "images": [
      "https://cdn.shopify.com/s/files/1/0607/2139/7918/files/Creamy_Mushroom_and_Thyme_Soup_480x480.jpg?v=1694797930",
    ]
  },

  "butternut-squash-ginger-soup": {
    "prep": "10 min",
    "cook": "20-25 min",
    "instructions": [
      "Heat olive oil in a large pot over medium heat. Add onion, salt, and several grinds of pepper; sauté until soft, about 5-8 minutes.",
      "Add garlic, ginger, cinnamon, and nutmeg. Stir and cook for about 1 minute until fragrant.",
      "Add butternut squash and broth. Bring to a boil, then reduce heat to a simmer. Cook uncovered for 15-20 minutes until squash is tender.",
      "Ladle soup into a blender in batches. Add mandarin orange juice and cashew cream. Blend until smooth and adjust seasoning as needed.",
      "Serve immediately, or return to stove to simmer and thicken. Top with a drizzle of cream, pumpkin seeds, salt, and pepper."
    ],
    "notes": "To make cashew cream: blend 1/2 cup raw cashews with 1 cup water in a high-speed blender for 1 minute; soaking not required. Soup stores in the fridge up to a week or freezer for three months.",
    "images": [
      "https://tastefulkitchen.com/wp-content/uploads/2025/07/BUTTERNUT-SQUASH-GINGER-e1758825554107.jpg",
      "https://nourishedbynutrition.com/wp-content/uploads/2020/10/Butternut-Squash-Soup-with-Orange-and-Ginger-10-1.jpg",
      "https://nourishedbynutrition.com/wp-content/uploads/2020/10/Butternut-Squash-Soup-with-Orange-and-Ginger-1-1.jpg",
      "https://nourishedbynutrition.com/wp-content/uploads/2020/10/Butternut-Squash-Soup-with-Orange-and-Ginger-3-1.jpg",
    ]
  },

  "truffle-whipped-mashed-potatoes": {
    "prep": "15 min",
    "cook": "15 min",
    "instructions": [
      "Place potatoes in a large pot and cover with water. Bring to a boil over high heat.",
      "Cook potatoes 12-14 minutes until fork-tender. Drain in a colander.",
      "Return potatoes to the pot. Add vegan butter, ½ cup milk, garlic, truffle oil, and salt.",
      "Mash potatoes to desired consistency. Add up to an additional ½ cup milk as needed.",
      "Taste and adjust seasoning with additional salt and pepper. Serve with chives and vegan gravy if desired."
    ],
    "notes": "These fluffy mashed potatoes are infused with the savory flavor of truffle oil and can be served as a side dish or with your favorite vegan gravy.",
    "images": [
      "https://tastefulkitchen.com/wp-content/uploads/2025/09/truffled-mashed-potatoes-1-of-1.jpg",
      "https://www.connoisseurusveg.com/wp-content/uploads/2018/11/truffled-mashed-potatoes-collage.jpg",
      "https://www.connoisseurusveg.com/wp-content/uploads/2018/11/truffled-mashed-potatoes-6-of-6.jpg",
    ]
  },

  "truffle-whipped-mashed-potatoes": {
    "prep": "15 min",
    "cook": "15 min",
    "instructions": [
      "Place potatoes in a large pot and cover with water. Bring to a boil over high heat.",
      "Cook potatoes 12-14 minutes until fork-tender. Drain in a colander.",
      "Return potatoes to the pot. Add vegan butter, ½ cup milk, garlic, truffle oil, and salt.",
      "Mash potatoes to desired consistency. Add up to an additional ½ cup milk as needed.",
      "Taste and adjust seasoning with additional salt and pepper. Serve with chives and vegan gravy if desired."
    ],
    "notes": "These fluffy mashed potatoes are infused with the savory flavor of truffle oil and can be served as a side dish or with your favorite vegan gravy.",
    "images": [
      "https://tastefulkitchen.com/wp-content/uploads/2025/09/truffled-mashed-potatoes-1-of-1.jpg",
      "https://www.connoisseurusveg.com/wp-content/uploads/2018/11/truffled-mashed-potatoes-collage.jpg",
      "https://www.connoisseurusveg.com/wp-content/uploads/2018/11/truffled-mashed-potatoes-6-of-6.jpg",
    ]
  },
  "balsamic-grilled-vegetables": {
    "prep": "10 min",
    "cook": "35-40 min",
    "instructions": [
      "Preheat oven to 475°F (245°C).",
      "Combine butternut squash, Yukon Gold potatoes, bell peppers, sweet potato, and red onion in a large bowl.",
      "In a small bowl, stir together olive oil, balsamic vinegar, rosemary, thyme, salt, and pepper. Pour over vegetables and toss to coat evenly.",
      "Transfer vegetables to a large roasting pan in an even layer.",
      "Roast in preheated oven, stirring every 10 minutes, until slightly caramelized and cooked through, about 35-40 minutes.",
      "Serve and enjoy!"
    ],
    "notes": "These roasted vegetables are perfect as a side dish or tossed into grain bowls. Adjust herbs as desired for flavor variation.",
    "images": [
      "https://www.allrecipes.com/thmb/Y8N4F6v-j_WhNlAOH8AgM2A6oMU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format/webp/AR-RM-9377-roasted-vegetables-ddmfs-step1-3x4-78119d6ecb914e219a08368b8fa17010.jpg",
      "https://www.allrecipes.com/thmb/wWUDm-HKDaA2wmykQ2O_cRmtQm0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format/webp/AR-RM-9377-roasted-vegetables-ddmfs-step2-3x4-3c365614c36044e6bc1500a0e45af12c.jpg",
      "https://www.allrecipes.com/thmb/pBzkiJMc7ncWgyyaiW-XrZSqshM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format/webp/AR-RM-9377-roasted-vegetables-ddmfs-step3-3x4-6ce66ba0f6cd448792d24ae23e2ad428.jpg",
      "https://www.allrecipes.com/thmb/KFl9lLnWkCbyqRkMU3WOGoOa8yk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format/webp/AR-RM-9377-roasted-vegetables-ddmfs-step5-3x4-1e61125c8965487b8783b521ce702a8d.jpg",
    ]
  },
  "edamame-sea-salt": {
    "prep": "5 min",
    "cook": "5 min",
    "instructions": [
      "Steam edamame briefly until warm.",
      "Top with sesame seeds and coarse sea salt.",
      "Serve immediately as a snack or appetizer. Can be prepared in large batches for catering events."
    ],
    "notes": "Edamame is high in protein and fiber. The pods are edible and the sesame seeds add a nutty flavor while the coarse salt adds crunch.",
    "images": [
      "https://tastefulkitchen.com/wp-content/uploads/2025/07/Edamame.png",
    ]
  },
  "avocado-mango-salsa": {
    "prep": "10 min",
    "cook": "0 min",
    "instructions": [
      "In a medium to large bowl, combine diced mango, red onion, cucumber, cherry tomatoes, jalapeños, orange juice, lime juice, and cilantro. Mix to combine.",
      "Allow the salsa to rest at room temperature or in the fridge for 20–30 minutes to let the flavors deepen.",
      "Before serving, add the diced avocado and gently mix to combine, taking care not to mash it. Adjust seasoning with salt and pepper."
    ],
    "notes": "Use about 3 medium Ataulfo/Honey mangos. For mild heat, use 1 jalapeño and remove membranes/seeds. For spicy, use 2–3 jalapeños and keep membranes/seeds. Dice larger tomatoes to match cucumber size.",
    "images": [
      "https://rainbowplantlife.com/wp-content/uploads/2020/05/Mango-Salsa-hero-2.jpg",
      "https://rainbowplantlife.com/wp-content/uploads/2020/05/Mango-Salsa-hero-5.jpg",
      "https://rainbowplantlife.com/wp-content/uploads/2020/05/mango-avocado-salsa-ingredients-shot.png",
    ]
  },
  "pineapple-teriyaki-tofu-puffs": {
    "prep": "15 min",
    "cook": "15 min",
    "instructions": [
      "Press the extra firm tofu, removing as much moisture as possible using a tofu press or heavy weight and paper towels for 15–30 minutes.",
      "Combine all tofu marinade ingredients in a medium bowl.",
      "Cut tofu into 1-inch cubes, place in a ziplock bag, add marinade, and refrigerate at least 15 minutes.",
      "Coat marinated tofu in cornstarch in a flat pan or plate. Optionally, spray lightly with vegetable oil for extra crispiness.",
      "Arrange tofu cubes in a single layer in the air fryer basket lined with parchment paper.",
      "Air-fry at 400°F (200°C) for 15 minutes, shaking or moving cubes halfway through.",
      "Serve baked tofu puffs garnished with sesame seeds and chopped green onion tops. Enjoy as a snack, in a rice bowl, Buddha bowl, or on salads."
    ],
    "notes": "Press tofu well to ensure crispiness. Variations: Spicy Teriyaki (add sriracha), Sesame Teriyaki (add tahini), Orange Teriyaki (add orange zest and juice). Store in fridge 3-4 days, or freeze up to 3 months.",
    "images": [
      "https://tastefulkitchen.com/wp-content/uploads/2025/06/pineappleteriyakitofu.png",
    ]
  },
};